// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8nK3YF13tH2GUNsENuQPIBRzRbHmcE4k',
    appId: '1:905800436454:web:2647e12a08c0f21acfc927',
    messagingSenderId: '905800436454',
    projectId: 'advance-todo-app-df878',
    authDomain: 'advance-todo-app-df878.firebaseapp.com',
    storageBucket: 'advance-todo-app-df878.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Md83xDmpRyvEpbtSC6iKuGALz_rfBDA',
    appId: '1:905800436454:android:9faf1cc3b793cc65cfc927',
    messagingSenderId: '905800436454',
    projectId: 'advance-todo-app-df878',
    storageBucket: 'advance-todo-app-df878.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8xCf3NiME-PsoWPAVIxDrNI03XDlPei8',
    appId: '1:905800436454:ios:4c8c222f69c04848cfc927',
    messagingSenderId: '905800436454',
    projectId: 'advance-todo-app-df878',
    storageBucket: 'advance-todo-app-df878.appspot.com',
    iosClientId: '905800436454-6mvnk7m5h3ejludrv0bvpet51fcqbhte.apps.googleusercontent.com',
    iosBundleId: 'com.example.advanceTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8xCf3NiME-PsoWPAVIxDrNI03XDlPei8',
    appId: '1:905800436454:ios:4c8c222f69c04848cfc927',
    messagingSenderId: '905800436454',
    projectId: 'advance-todo-app-df878',
    storageBucket: 'advance-todo-app-df878.appspot.com',
    iosClientId: '905800436454-6mvnk7m5h3ejludrv0bvpet51fcqbhte.apps.googleusercontent.com',
    iosBundleId: 'com.example.advanceTodoApp',
  );
}
